IMAGE_NAME = "bento/ubuntu-20.04"
N = 1

Vagrant.configure(2) do |config|     

    config.vm.provision "file", source: "~/.ssh/vagrant_key.pub", destination: "/home/vagrant/.ssh/vagrant_key.pub"
    config.vm.provision :shell, :inline => "cat /home/vagrant/.ssh/vagrant_key.pub >> /home/vagrant/.ssh/authorized_keys", run: "always"

    # Configure master node  
    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.56.15"
        master.vm.hostname = "k8s-master"
        master.vm.provider "virtualbox" do |v|
            v.memory = 2048
            v.cpus = 2
        end
    end

    # Configure worker nodes
    (1..N).each do |i|
        config.vm.define "worker#{i}" do |worker|
            worker.vm.box = IMAGE_NAME
            worker.vm.network "private_network", ip: "192.168.56.#{i+15}"
            worker.vm.hostname = "worker#{i}"
            worker.vm.provider "virtualbox" do |v|
                v.memory = 2048
                v.cpus = 2
            end
        end
    end
end
